# $FreeBSD$

PKGNAMESUFFIX=	-bananapro

COMMENT=	Cross-build U-Boot loader for Banana Pi Pro

LICENSE=	GPLv2

# Local overrides
MASTERDIR=	${.CURDIR}/../u-boot-cubieboard
DESCR=		${.CURDIR}/pkg-descr
MODEL=		bananapro
CONF_TARGET=	Bananapro_defconfig

.include "${MASTERDIR}/Makefile"
